Numpy kutubxonasi 

In [1]:
import numpy as np #numpy kutubxonasini chaqirib olish

In [2]:
my_list = list(range(100000)) # python list
my_array = np.array(range(100000)) # numpy array

#array

In [4]:
data = [3.5, 4, 6, 2] # list
arr = np.array(data) # array
arr

array([3.5, 4. , 6. , 2. ])

#ndim

In [5]:
arr.ndim # arrayning o'lchami

1

In [6]:
data2 = [[1,2,3], [4,5,6]] # nested list
arr2 = np.array(data2)
arr2.ndim

2

#shape

In [7]:
arr2.shape # massivning hajmi ya'ni qator va ustunlar soni (q, u)

(2, 3)

#size

In [8]:
arr2.size # massivning elementlari soni

6

#zeros

In [9]:
arr3 = np.zeros((2,4)) # barcha elementlari 0 ga teng bo'lgan (2, 4) hajmli massiv yaratib beradi
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#ones

In [10]:
arr4 = np.ones((3,2)) # barcha elementlari 1 ga teng bo'lgan (3, 2) hajmli massiv yaratib beradi
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#arange

In [11]:
arr5 = np.arange(4, 40, 2) # 4 dan 40 gacha qiymatlarni 2 qadam bilan massivga joylab beradi
arr5

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

#dtype

In [13]:
arr2.dtype # massivning ma'lumot turini aniqlab beradi

dtype('int64')

#astype

In [14]:
int_arr = np.array([2, 5, 7, 3, 16])
float_arr = int_arr.astype(np.float64) # int tipidan float64 tipiga o'tkazib beradi
float_arr.dtype

dtype('float64')

Indekslash va kesib olish (slicing)

In [15]:
arr = np.arange(10, 100, 10)
arr[3:5] # massivning 3-dan 5-indeksigacha kesib oladi. 5-indeks kirmaydi

array([40, 50])

#copy

In [16]:
sliced_arr = arr[3:5].copy() # kesib olinga massivning qismini nusxasini alohida boshqa massivga o'zlashtirib olyapmiz

#slicing 2d

In [17]:
arr2d = np.array([[1,2,3], [4,5,6]]) # 2 o'lchamli massiv
arr2d[1, 1:] # 2 o'lchamli massivdan 1-qator, 1- va 2-ustunlarni qirqib olish

array([5, 6])

#slicing 3d

In [19]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) # 3 o'lchamli massiv
arr3d[1][0, 1:] # 8 va 9 sonlarini kesib olish

array([8, 9])

Boolean indekslash

In [23]:
names = np.array(['Ali', 'Umid', 'Otabek', 'Aziz', 'Ali', 'Nodir'])
data = np.random.randn(6,4)
data

array([[-0.28897701, -0.52120235, -0.13872449, -1.89229199],
       [-0.28329497, -0.45682998, -2.44524192,  0.10604978],
       [ 0.20256575, -0.02716926,  0.76061159,  0.57280381],
       [-1.82382968, -1.57023409, -2.64425713,  2.18244657],
       [-0.5857591 , -0.5015264 , -1.58191766, -0.30340154],
       [ 2.17526144, -0.40125367,  0.08096716,  1.96456697]])

In [21]:
data[names=='Umid'] # Umidga tegishli ma'lumotlar

array([[-0.52920159, -0.38394441,  0.52325557,  0.12831395]])

In [24]:
data[names=='Ali', 2:] # Aliga tegishli ma'lumotlarning 2-chi ustunidan oxirgi ustunigacha chiqaradi

array([[-0.13872449, -1.89229199],
       [-1.58191766, -0.30340154]])

Array o'qlarini almashtirish (Transpose)

#reshape

In [25]:
a = np.arange(6).reshape(3, 2) # 6 gacha bo'lgan assivni (3, 2) hajmda qilib beradi
a

array([[0, 1],
       [2, 3],
       [4, 5]])

#transpose (T)

In [26]:
a.T # a massivni transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

#swaping axes

In [27]:
a.swapaxes(1, 0) # a massivni transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

#dot

In [28]:
np.dot(a, a.T) # transposening ishlatilishiga bir misol

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

Universal funksiyalar

#sqrt

In [29]:
arr = np.arange(10)
np.sqrt(arr) # kvadrat ildizini hisoblaydi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#square

In [30]:
np.square(arr) # kvadratini hisoblaydi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#eksponenti

In [31]:
np.exp(arr) # eksponentini hisoblaydi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#logarifm

In [32]:
np.log(arr) # e asosga ko'ra logarifmni hisoblaydi

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#modf

In [33]:
arr1 = np.array([1.4, 4.2, 9.6, 12.43, 3.09])
q, b = np.modf(arr1) # modf sonlarni qoldiq va butun qismini alohida qilib ajratib beradi.
print(q) # qoldiq
print(b) # butun

[0.4  0.2  0.6  0.43 0.09]
[ 1.  4.  9. 12.  3.]


#sign

In [38]:
arr2 = np.random.randn(2, 4)
np.sign(arr2) # massiv elementi agar manfiy bo'lsa -1, musbat bo'lsa 1 qaytaradi

array([[ 1.,  1.,  1., -1.],
       [ 1.,  1.,  1., -1.]])

#isnan

In [39]:
arr2[0, 1]=np.NaN # arr2 ning 0-qator, 1-elementini NaN qiymatga o'zgartirdik
np.isnan(arr2) # NaN qiymat bo'lsa True, aks holda Fasle qaytaradi

array([[False,  True, False, False],
       [False, False, False, False]])

Binary funksiyalar

#add

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.add(arr1, arr2) # 2 ta massivning mos elementlarini bir-biriga qo'shadi

array([5, 7, 9])

#multiply

In [41]:
np.multiply(arr1, arr2) # 2 ta massivning mos elementlarini bir-biriga ko'paytiradi

array([ 4, 10, 18])

#maximum

In [42]:
arr1 = np.array([23, 12, 67, 41])
arr2 = np.array([11, 22, 34, 98])
np.maximum(arr1, arr2) # 2 ta massivning mos elementlarini solishtiradi va kattasini oladi

array([23, 22, 67, 98])

Mantiqiy shart operatori

#where

In [44]:
from numpy.core.multiarray import result_type
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
# Shart
cond = np.array([True, False, True, True, False])
#where
result = np.where(cond, xarr, yarr) # agar shart True bo'lsa xarr elementini oladi, False bo'lsa yarr elementini oladi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [45]:
arr = np.random.randn(4,4)
results = np.where(arr<0, -2, 2)
results

array([[ 2,  2, -2,  2],
       [ 2,  2,  2,  2],
       [ 2, -2, -2, -2],
       [-2,  2, -2,  2]])

Matematik va statistik usullarni qo'llash

#sum

In [46]:
arr = np.random.randn(5, 4)
arr.sum() # massiv elementlari yig'indisi
np.sum(arr) # massiv elementlari yig'indisi

-10.4870379007176

In [47]:
arr.sum(axis=0) # har bir qatorning ustunlari yig'indisi

array([-2.37714431, -4.97184913, -1.27427221, -1.86377225])

In [48]:
arr.sum(axis=1) # har bir ustunning qatorlari yig'indisi

array([-1.00859081, -2.68655672, -1.43165604, -3.9210316 , -1.43920274])

#mean

In [50]:
arr.mean() # massiv elementlarining o'rtacha qiymati

-0.52435189503588

In [51]:
np.mean(arr) # bu ham massiv elementlarining o'rtacha qiymati

-0.52435189503588

In [55]:
arr.mean(axis=0) # har bir ustunning o'rtacha qiymati

array([-0.47542886, -0.99436983, -0.25485444, -0.37275445])

In [56]:
arr.mean(axis=1) # har bir qatorning o'rtacha qiymati

array([-0.2521477 , -0.67163918, -0.35791401, -0.9802579 , -0.35980068])

#cumsum

In [57]:
data = np.arange(6)
data.cumsum() # bu cumulative sum ya'ni o'zigacha bo'lgan sonlarni yig'indisi

array([ 0,  1,  3,  6, 10, 15])

Tartiblash (Sorting)

#sort

In [58]:
# 1-usul
arr = np.array([23, 12, 4, 3, 17, 9]) # tartiblanmagan array
sorted_arr = np.sort(arr) # tartiblangan array
sorted_arr

array([ 3,  4,  9, 12, 17, 23])

In [59]:
# 2-usul
arr.sort() # massivni tartiblab yana o'ziga o'zlashtiradi
arr

array([ 3,  4,  9, 12, 17, 23])

In [61]:
# teskari tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([23, 17, 12,  9,  4,  3])

#sort 2d

In [67]:
arr2d = np.random.randn(2,4)
arr2d

array([[ 0.89884929, -0.05148628, -1.47396789, -1.80488591],
       [ 0.700325  , -2.14530228, -0.57821241, -1.00848577]])

In [69]:
row_arr = np.sort(arr2d, axis=0) # har bir ustunni tartiblaydi
row_arr

array([[ 0.700325  , -2.14530228, -1.47396789, -1.80488591],
       [ 0.89884929, -0.05148628, -0.57821241, -1.00848577]])

In [70]:
col_arr = np.sort(arr2d, axis=1) # har bir qatorini tartiblaydi
col_arr

array([[-2.14530228, -1.80488591, -1.47396789,  0.700325  ],
       [-1.00848577, -0.57821241, -0.05148628,  0.89884929]])

Takrorlanmas va boshqa amallar

#unique

In [71]:
names = np.array(['Ali', 'Hasan', 'Zokir', 'Ali', 'Husan', 'Hasan', 'Umid'])
np.unique(names) # faqat takrorlanmas, takrorlansa ham faqat bittasini qaytaradi

array(['Ali', 'Hasan', 'Husan', 'Umid', 'Zokir'], dtype='<U5')

#in1d

In [72]:
arr1 = np.array([2, 5, 3, 9, 0, 4])
arr2 = np.array([4, 9, 12, 8])
np.in1d(arr1, arr2) # arr1 lementlari arr2 elementlari ichida bo'lsa True, aks holda False qaytaradi

array([False, False, False,  True, False,  True])

#setdiff1d

In [73]:
np.setdiff1d(arr1, arr2) # 2 tammasivni taqqoslaydi va arr1 elementlarida arr2 elementlari mavjud bo'lmagan qiymatlarni qaytaradi

array([0, 2, 3, 5])

Fayllar bilan ishlash

#save

In [74]:
arr = np.arange(10)
np.save('data', arr) # data nomli fayl yaratib shunga arr ni saqlash
np.load('data.npy') # data nomli faylni o'qish
arr2 = np.load('data.npy') # o'zgaruvchiga yuklash

#savez

In [75]:
arr1 = np.arange(20)
np.savez('arrays', a=arr, b=arr1) # arrays fayliga arr, arr1 massivlarini saqlash

In [80]:
arrays = np.load('arrays.npz') # fayldan o'qib, o'zgaruvchiga saqlash


In [81]:
arrays['a'] # arr ni o'qish 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#savez_compressed

In [82]:
np.savez_compressed('array.comp.npz', a=arr, b=arr1) # siqilgan holda saqlash